language: generic

sudo: true
group: travis_latest

matrix:
  include:
  - name: "Auth - Unit Tests"
    env:
      - MODULE=auth
      - TARGET=test
  - name: "Auth - Memory Leaks"
    env:
      - MODULE=auth
      - TARGET=memleak
  - name: "Gateway - Unit Tests"
    env:
      - MODULE=gateway
      - TARGET=test
  - name: "Sonar"
    if: branch = master
    env:
      - MODULE=.
      - TARGET=sonar

os:
  - linux

git:
  depth: 3
  quiet: true

install:
  - sudo apt-get install -y valgrind
  - wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
  - unzip build-wrapper-linux-x86.zip
  - export PATH="$PATH:$(pwd)/build-wrapper-linux-x86"
  - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227.zip
  - unzip sonar-scanner-cli-3.2.0.1227.zip
  - export PATH="$PATH:$(pwd)/sonar-scanner-3.2.0.1227/bin"

script:
  - make -C $MODULE $TARGET
