language: generic

sudo: true
group: travis_latest

matrix:
  include:
  - name: "Unit Tests"
    env: TARGET=test
  - name: "Memory Leaks"
    env: TARGET=memleak

os:
  - linux

git:
  depth: 3
  quiet: true

before_install:
  - sudo apt-get install -y valgrind

install:
  make -C authenticator/ compile
  
script:
  - make -C authenticator/ $TARGET
