language: generic

sudo: true
group: travis_latest

matrix:
  include:
  - name: "Unit Tests"
    env: TARGET=test
  - name: "Memory Leaks"
    env: TARGET=memleak
  - name: "Sonar"
    if: branch = master
    env: TARGET=sonar

os:
  - linux

git:
  depth: 3
  quiet: true

before_install:
  - sudo apt-get install -y valgrind
  - wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
  - unzip build-wrapper-linux-x86.zip
  - export PATH="$PATH:$(pwd)/build-wrapper-linux-x86"
  - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227.zip
  - unzip sonar-scanner-cli-3.2.0.1227.zip
  - export PATH="$PATH:$(pwd)/sonar-scanner-3.2.0.1227/bin"

install:
  make -C auth/ compile
  
script:
  - make -C auth/ $TARGET
